Первые три задачи по теме Числа
sadnaastasia/project pull request #4
Opened 2023-11-24 21:15 UTC by sadnaastasia

2023-12-08 15:17 UTC, Starotitorov requested changes

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/2/lesson2.js
> +  let result = arr.filter(item => item >= a && item <= b);
You don't need to define a new variable when you just want to return the result from the function.

```
function filterRange(arr, a, b) {
    return arr.filter(item => item >= a && item <= b);
}
```

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 2/2/lesson2.js
> +alert( Math.round(6.35 * 100) / 100 );
You didn't solve the task. You need to round `6.35` to `6.4` two ways using `toFixed` and `Math.round`. The result is wrong in both cases right now.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 2/3/lesson3.js
> +        numberStr = prompt('Введите число','0');
Why do you pass `'0'` as the default input value here?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 2/3/lesson3.js
> +    return numberStr;
The function needs to return either `number` or `null`. What's the return value type here?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 2/3/lesson3.js
> +            return null; break;
Why do you need `break` after the return statement?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 2/3/lesson3.js
> +        if (numberStr === '' || numberStr === null){
It seems we can move these checks outside the `while` loop.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 3/1/lesson1.js
> +  str = str[0].toUpperCase() + str.slice(1);
You forgot to declare a variable here. Also, you don't actually need a variable when you want to return a value from the function.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 3/2/lesson2.js
> +  for (let letter of str) {
What is this? Do you understand what's going on in your code? Also, the formatting is poor.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 3/3/lesson3.js
> +    return str = str.slice(0,maxlength-1) + '…';
Why do you assign a value to `str` and return it?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 4/4/lesson4.js
> +      for (let key = 0; key < inputArray.length; key++) {
Why do you need another `for` loop? You can solve the task either by relying on the `sumInput` variable or using an array of numbers. When you use the first approach, you don't need an array at all. If you decide to use an array, you don't need the `sumInput` variable.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 4/5/lesson5.js
> +    for (let key of arr) {
What is `key` here?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/1/lesson1.js
> +  str = arr.join('');
Mutating the input parameters of a function is considered to be a bad practice. You don't need to do it. You just need to return a new string from the function.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/10/lesson10.js
> +    for (let i = array.length - 1; i > 0; i--) {
Could you rewrite the code in a way that here we go from `0` to `array.length - 1`?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/11/lesson11.js
> +  return arr.reduce((sum, user) => sum + user.age, 0) / users.length;
Where is `arr` declared? You pass the array to the function using the `users` parameter.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/5/lesson5.js
> +    for (let i = 0; i < arr.length; i++) {
You can use the `slice` method instead of writing a loop.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/7/lesson7.js
> +// let result = [];
I have plenty of questions about the code in the comments. It's better to discuss all of them on a call.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/9/lesson9.js
> +function sortByAge(a, b) {
You can also write it the next way. You've already done something similar in one of the tasks.
```
function sortByAge(a, b) {
    return a.age - b.age;
} 
```

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework/homework.js
> +  cycl: for (let i = 0; i < arr.length - 1; i++) {
It's a bad practice to use labels like `cycl` in JavaScript. Most of the time you don't need them. Almost any code can be rewritten without them.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework/homework.js
> +        result = true; break cycl;
If we find at least one duplicate, does it make sense to continue the execution?

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework/homework.js
> +      } result = false; continue;
You don't need `continue` here. The next iteration of the cycle will be started anyway.

2023-12-08 15:17 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework/homework.js
> +  let result;
Do we need the `result` variable? Can we rewrite the code without using it?

2023-12-09 21:58 UTC, sadnaastasia commented on Chapter 5/Lesson 2/3/lesson3.js
> +    return numberStr;
😕 string

2023-12-09 22:31 UTC, sadnaastasia commented on Chapter 5/Lesson 4/4/lesson4.js
> +      for (let key = 0; key < inputArray.length; key++) {
in exercise we should use the array (Напишите функцию sumInput(), которая:

Просит пользователя ввести значения, используя prompt и сохраняет их в массив.
Заканчивает запрашивать значения, когда пользователь введёт не числовое значение, пустую строку или нажмёт «Отмена».
Подсчитывает и возвращает сумму элементов массива.)

2023-12-09 22:33 UTC, sadnaastasia commented on Chapter 5/Lesson 4/5/lesson5.js
> +    for (let key of arr) {
number

2023-12-11 16:26 UTC, Starotitorov requested changes

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 2/2/lesson2.js
>  alert( 6.35.toFixed(20) ); //6.34999999999999964473
This line still produces an invalid result.

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 2/3/lesson3.js
> +    return numberStr;
Yes, and it needs to return a number or null.

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 3/2/lesson2.js
> +  if ((str.toUpperCase().includes('XXX')) || (str.toLowerCase().includes('viagra'))) {
```
function checkSpam(str) {
    return str.toUpperCase().includes('XXX') || str.toLowerCase().includes('viagra');
}
```

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 4/4/lesson4.js
> +  for (let input of inputArray) {
You can use `reduce` instead.

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 5/7/lesson7.js
> +    result = [];
Where is the variable declared?

2023-12-11 16:26 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/2/homework.js
> +const posts = [
Could we move all tasks related to the homework to one file? You can define a function with a descriptive name for every task from the list.

2023-12-11 19:22 UTC, sadnaastasia commented on Chapter 5/Lesson 2/2/lesson2.js
>  alert( 6.35.toFixed(20) ); //6.34999999999999964473
yes, because this line is just for me to see why it doesn't work

2023-12-11 19:25 UTC, Starotitorov commented on Chapter 5/Lesson 2/2/lesson2.js
>  alert( 6.35.toFixed(20) ); //6.34999999999999964473
And you need to make it work using the `toFixed` method 😄 .

2023-12-17 13:32 UTC, Starotitorov requested changes

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/10/lesson10.js
> +      let j = Math.ceil(Math.random() * (i + 1));
This is incorrect when you iterate from `0` to `arr.length - 1`. You need to select an index `j` between `i` and `arr.length-1` here.

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
> +  arr.sort(compareNumeric);
It's a bad practice to mutate input parameters.

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
> +console.log(findMissingNumber(arrayOfIntegers)); // 8
Your solution produces an invalid result when `const arrayOfIntegers = [2, 5, 1, 4, 8, 6, 3, 7];`.
```
const arrayOfIntegers = [2, 5, 1, 4, 8, 6, 3, 7];
console.log(findMissingNumber(arrayOfIntegers)); // 9
```

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// let onlyBody = posts.map (post => post.body);
It's better to create a function for every task in the list. I can't review the code in the comments.

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +            arr[value.id] = value;
Is `arr` an array?

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    function groupById(arr) {
I like that you moved the code used several times to a separate function 👍 .

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +function normalizeState(arr) {
It's better to choose a more descriptive input parameter name.

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let posts = arr.reduce((posts, value) => {
What's going on here? Why do we need this code?

2023-12-17 13:32 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    arr.posts = {};
What is `arr` here? Why do we need to mutate the input parameter value?

2023-12-30 13:10 UTC, Starotitorov requested changes

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function showOnlyBody(posts) {
It's better to give a more descriptive name. For example, `getPostBodies` or `mapPostsToPostBodies`.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function filterPosts(posts) {
It's better to specify a filtration criterion in the function name. You can go even further and pass the required minimum number of comments in the function parameters.

```
function filterPostsByCommentsLength(posts, minNumberOfComments) {}
```

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     let postFiltered = posts.filter(post => post.comments.length >= 2);
There is no need to define a variable when you plan to return the value from the function immediately.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function filterByComments(posts) {
The same as above. The function name needs to be descriptive. For example, `filterPostsByNumberOfLikesInComments`. You can also define a parameter to pass the required minimum number of likes.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//         for (let i = 0; i < post.comments.length; i++) {
I think an Array method `every` could help you here 😉 .

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function calculateTheTotalSumOfLikesUnderAllPosts(posts) {
I like that this function has a descriptive name. Well done 👍 . Articles are usually omitted in function names, so it can be called `calculateTotalNumberOfLikesUnderAllPosts`.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function findMostPopularPost(posts) {
I like the function name 👍 .

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     posts.reduce((mostPopularPost, post) => {
I think you forgot to return the value from the function.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//         mostPopularPost :
The indentation isn't great here.

```
return mostPopularPost.numberOfLikes > post.numberOfLikes
    ? mostPopularPost
    : post;
```

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function findmostPopularComment(posts) {
A minor thing, but I think it should be `findMostPopularComment`.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     posts.reduce((mostPopularComment, post) => {
In general, there are several ways you can approach the task.

1. You can use one reduce call to find the most popular comment under all posts.
2. You can write a function to get a list of comments under all posts. This function can be reused later in task 7. Also, you can write a function `findMostPopularEntity` that can be used in tasks 5 and 6. The consecutive use of the functions can help you to solve task 6 😉 .

I'd recommend you choose the latter.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     let maxLikes = 0;
You don't need this variable. Check task 5.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     let comments = posts.reduce((comments, post) => {
Could you check my comment on task 6?

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function getCommentsAndSort(posts) {
The function needs to return a value.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//         for (let i = 0; i < post.comments.length; i++) {
You don't need another loop.

```
let comments = posts.reduce((allComments, post) => {
    return allComments.concat(post.comments);
}, []);
```

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     comments.sort((a, b) => {
I've decided to make the task more interesting 😄 . You need to sort the comments by the number of likes. In case 2 comments have the same number of likes, they need to be sorted in alphabetical order by text.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +// function showOnlyBody(posts) {
Could you please uncomment the code and add `console.log` to every function call so the result is printed to the console?

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
>  function findMissingNumber(arr) {
Let me give you a hint by providing you with another task 😉 . Imagine you have `5` water buckets: `1` litre, `2` litres, `3` litres, `4` litres, `5` litres buckets, and a barrel containing  `15` litres of water. You've lost one of the buckets that can be filled with `x` litres of water. Now you decide to fill the remaining buckets with the maximum amount of water they can take. How many litres are left in the barrel after that?

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/10/lesson10.js
> +    let j = Math.ceil(Math.random() * (arr.length - i));
You can have a bug when `j` is `0` because you use `array[array.length - j]` later.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/18/2/lesson2.js
> +function topSalary(salaries) {
Something is wrong with lesson numbers. It's lesson 10.

2023-12-30 13:10 UTC, Starotitorov commented on Chapter 5/Lesson 5/18/2/lesson2.js
> +      return [maxSalary] = salary;
I don't understand what's going on here. `maxSalary` is an array. The variable name doesn't display this fact.

2023-12-31 12:45 UTC, sadnaastasia commented on Chapter 5/Lesson 5/homework2/homework.js
> +//     comments.sort((a, b) => {
......................🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄

2024-01-03 11:20 UTC, Starotitorov requested changes

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
>  function findMissingNumber(arr) {
You've got the idea correctly 👍

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
> +  for (let i = 1; i < arr.length + 2; i++) {
That's is right. At the same time, you can simplify this by using the formula to calculate the sum of N members of an arithmetic progression:

```
Sn = (a1 + an) * n / 2
```

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +        if (post.comments.every((comments) => comments.numberOfLikes >= minNumberOfLikes)) return post;
The function passed to `filter` needs to return a boolean value, so you simplify this.

```
let postFilteredByComments = posts.filter(post => post.comments.every(comments => comments.numberOfLikes >= minNumberOfLikes))
```

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let mostPopularComment = findMostPopularEntity(comments);
Great job 👍

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +function getCommentsAndSort(posts) {
I think it's better to choose a more descriptive name. For example, `getSortedListOfComments` or `getCommentListSortedByLikes`.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    comments.sort((a, b) => {
You forgot to return a value from the function.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +function findTheAuthorOfTheMostComments(posts) {
Articles are usually omitted in function names.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let athorsOfComments = posts.reduce((author, post) => {
A minor misspelling.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +        for (let i = 0; i < post.comments.length; i++) {
Can we simplify this by using `map` and `concat` methods of `Array`? Also, `author` is an array, but the variable name doesn't display this fact.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    for (let i = 0; i < athorsOfComments.length - 1; i++) {
Let's consider the case when the author left 3 comments. Will this code produce the correct result?

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +        for (let i = 0; i < post.comments.length; i++) {
It makes sense to move this logic to a separate function.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 10/2/lesson2.js
> +      return [arrayOfPersonWithMaxSalaryAndHisSalary] = salary;
I don't get what you're doing here. Why do you create an array in which the first element is another array? What do you expect to return from the function in this case? It makes sense to debug the code.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 7/2/lesson2.js
> +function aclean(arr) {
The function produces a wrong result in the following case:

```
let arr = ["nap", "teachers", "cheaters", "PAN", "ear", "era", "hectares", "text"];`
console.log(aclean(arr)); // ["nap", "teachers", "ear", "text"];
```

The task is in the lesson about `Map` and `Set`, so it makes sense to check whether we can use one of the data structures to solve it.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 9/1/lesson1.js
> +  for (let salary of Object.values(obj)) {
How can we simplify this by using the `reduce` method of `Array`?

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 9/2/lesson2.js
> +  for (let key of Object.keys(obj)) {
The length of `arr` equals `Object.keys(obj)`. How can you get an array length in JavaScript.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/2/lesson2.js
> +//   let weekDay = (date.getDay() == 0) ? weekday = 'ВС' :
It's a bad practice to use nested ternary operators in JavaScript. It's better to use the switch statement instead. At the same time, I like the idea of using an array of days more.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/3/lesson3.js
> +    let day = [7, 1, 2, 3, 4, 5, 6];
I don't see much sense in using an array here because for all the numbers except the first one index equals value. We can just handle `0` separately.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/8/lesson8.js
> +  difference < 1000 ? result = 'прямо сейчас' :
It's a bad practice to use nested ternary operators. Also, the ternary operator is used when a value needs to be returned. If you don't need to return a value, it's better to use a conditional or switch statement.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/8/lesson8.js
> +  difference < 60 * 1000 ? result = `${difference / 1000} сек. назад` :
Don't forget to round values.

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/6/lesson6.js
> +    return (day - dayStart) / 1000;
Shouldn't we round the value to get a whole number?

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 11/7/lesson7.js
> +    return (dayTomorrow - day) / 1000;
Shouldn't we round the value to get a whole number?

2024-01-03 11:20 UTC, Starotitorov commented on Chapter 5/Lesson 12/1/lesson1.js
> +let userJson = JSON.parse(json);
`JSON.parse` returns an Object, Array, string, number, boolean, or null value corresponding to the given JSON text.

2024-01-28 18:26 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
> +  let sumN = (1 + Math.max(...arr)) * (arr.length + 1) / 2;
Could you let me know what you did here? Didn't we agree that we don't need to sort anything? Also, the formula is `Sn = (a1 + an) / 2 * n`.

2024-01-28 18:26 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    for (let i = 0; i < athorsOfComments.length - 1; i++) {
Don't forget about this.

2024-01-28 18:26 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    for (let i = 0; i < athorsOfComments.length - 1; i++) {
You can create a map storing authors and corresponding numbers of comments. This will allow you to find the author who wrote the most comments.

2024-02-07 18:34 UTC, Starotitorov requested changes

2024-02-07 18:34 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    for (let i = 0; i < arrayOfAuthorsOfComments.length; i++) {
Could we use `reduce` here?

2024-02-07 18:34 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    for (let entry of mapOfAuthorsAndNumberOfComments.entries()) {
Could we use `reduce` here?

2024-02-07 18:34 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/1/lesson1.js
> +    sum -= arr[i];
This isn't a trivial solution, but it looks good 👍 .

2024-03-26 15:03 UTC, Starotitorov requested changes
Great job 👍 . You're almost there. I've left a couple of comments. Once they're resolved, we can merge the pull request.

2024-03-26 15:03 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let postFilteredByComments = posts.filter(post => post.comments.every(comments => comments.numberOfLikes >= minNumberOfLikes));
You have an array of posts here, so it should be `postsFilteredByComments`.

2024-03-26 15:03 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let authorOfMostComments = arrOfAuthorsAndNumberOfComments.reduce(function(authorOfMostComments, author) {
The idea is correct, but I don't like the variable names. `authorOfMostComments` and `author` are array, but their values are obvious based on the context, so we can replace them with `resultPair` and `currentPair`. `authorOfMostComments` is an array, don't forget to display this fact in the variable name.

2024-03-26 15:03 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    return authorOfMostComments[0];
Your task is to find the name of the person who left the most comments. Currently, you know only the id.

2024-03-28 17:53 UTC, Starotitorov requested changes

2024-03-28 17:53 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +        if (obj.hasOwnProperty(author.name)) {
You can't use a name as a key here. `id` is unique, but `name` isn't. You can have 2 different users with the same name.

2024-03-28 17:53 UTC, Starotitorov commented on Chapter 5/Lesson 5/homework2/homework.js
> +    let arrOfAuthorOfMostComments = arrOfAuthorsAndNumberOfComments.reduce(function(resultPair, currentPair) {
`arrOfAuthorOfMostComments` can be replaced with `resultPair`.

2024-04-14 17:53 UTC, Starotitorov commented
I think we can merge the pull request.

That's why it's important to add files to .gitignore. You have merge conflicts that need to be resolved manually. You can read more about merge conflicts [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line).

Enter the following commands in the terminal.

```
git checkout master
git merge Chapter5
```

You'll see in the console that conflicts need to be resolved. You can enter `git status` to see the file containing the conflicts. In your case, you can just remove the hidden file `.DS_Store`.

```
git rm .DS_Store
git commit -m "Resolve merge conflict by deleting .DS_Store"
```

If everything is OK, you can push changes.

It's better to create `.gitignore` in the roo folder and add `.DS_Store` there.

2024-05-05 20:02 UTC, merged